<?php

namespace Swissup\Ignition\Model;

use Magento\Csp\Helper\CspNonceProvider;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Session\SessionManagerInterface;

class IgnitionNonceProvider
{
    public function __construct(
        private RequestInterface $request,
        private SessionManagerInterface $session
    ) {
    }

    public function saveNonce(string $nonce)
    {
        $this->session->setData('swissup_ignition_nonce', $nonce);
    }

    public function generateNonce(): string
    {
        $nonce = '';

        if ($this->request->isAjax()) {
            // Use previously generated nonce because we will show
            // popup on the page generated by previous request
            $nonce = (string) $this->session->getData('swissup_ignition_nonce');
        } elseif (class_exists(CspNonceProvider::class)) {
            $nonce = ObjectManager::getInstance()
                ->get(CspNonceProvider::class)
                ->generateNonce();
        }

        return $nonce;
    }
}
